# Generated by Django 6.0.6 on 2026-09-17 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='heure de début')),
                ('end_time', models.TimeField(verbose_name='heure de fin')),
                ('location_kind', models.CharField(choices=[('online', 'En ligne'), ('onsite', 'Sur place')], default='onsite', max_length=10, verbose_name='type de lieu')),
                ('location_label', models.CharField(blank=True, help_text='Laisser vide pour le déduire du lieu (« En ligne », ou la ville).', max_length=120, verbose_name='libellé du lieu')),
                ('online_url', models.URLField(blank=True, verbose_name='lien de visioconférence')),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='adresse')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name="complément d'adresse")),
                ('postal_code', models.CharField(blank=True, max_length=16, verbose_name='code postal')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_published', models.BooleanField(default=True, help_text="Décocher pour préparer un atelier sans l'afficher sur le site.", verbose_name='publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'atelier',
                'verbose_name_plural': 'ateliers',
                'ordering': ['date', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='agenda_event_ends_after_it_starts')],
            },
        ),
    ]
