# Generated by Django 6.0.6 on 2026-09-17 13:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, help_text='Note affichée sous les tarifs de ce groupe.', verbose_name='description')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage : le plus petit nombre en premier.", verbose_name='position')),
                ('is_published', models.BooleanField(default=True, verbose_name='publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'type de tarif',
                'verbose_name_plural': 'types de tarif',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='libellé')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='En euros. Laisser vide si le tarif est sur devis.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='montant')),
                ('on_demand', models.BooleanField(default=False, help_text="Cocher pour afficher « Sur devis » à la place d'un montant.", verbose_name='sur devis')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('is_published', models.BooleanField(default=True, verbose_name='publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.pricingtype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'tarif',
                'verbose_name_plural': 'tarifs',
                'ordering': ['position', 'description'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('amount__isnull', True), ('on_demand', True)), models.Q(('amount__isnull', False), ('on_demand', False)), _connector='OR'), name='pricing_price_amount_xor_on_demand')],
            },
        ),
    ]
