# Generated by Django 6.0.6 on 2026-09-22 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='avis')),
                ('author', models.CharField(max_length=100, verbose_name='nom')),
                ('context', models.CharField(blank=True, help_text="Par ex. « Atelier découverte », « Parent d'élève ».", max_length=100, verbose_name='description')),
                ('is_published', models.BooleanField(default=True, help_text="Décocher pour garder l'avis sans l'afficher sur le site.", verbose_name='publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ajouté le')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'avis',
                'ordering': ['-created_at'],
            },
        ),
    ]
