# Generated by Django 6.0.6 on 2026-09-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'avis', 'verbose_name_plural': 'avis'},
        ),
    ]
