/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The published, still-upcoming workshops, soonest first.
         *
         *     Public: this is the same content the website already shows to anyone, so requiring a
         *     token would only complicate the caller. DRF's project default is IsAuthenticated, so
         *     the AllowAny here is a deliberate, visible exception rather than a missing setting.
         *
         *     Pagination is off. The list is a handful of rows, and an unpaginated response makes
         *     the generated TypeScript type a plain array instead of {count, next, previous,
         *     results} — the frontend maps over it directly.
         */
        get: operations["events_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness probe used by the dev stack's healthcheck. Public — no auth required. */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing-types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The published tariff groups, each with its published lines nested.
         *
         *     Public and unpaginated for the same reasons as the agenda's list view: the content is
         *     already on the website, and a plain array generates a plain TypeScript array.
         */
        get: operations["pricing_types_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A workshop as the public agenda needs it.
         *
         *     Values go out machine-readable — an ISO date, ISO times, a location kind — and the
         *     frontend renders them with Intl.DateTimeFormat("fr-FR"). Formatting here instead would
         *     put French display strings in the database's contract and make the data unsortable
         *     again, which is the exact problem this replaced.
         *
         *     The postal address is flattened into a single `address` string: the site shows one
         *     line, and the separate fields exist so the admin form can guide input, not because
         *     anything downstream wants them apart.
         */
        Event: {
            /** Format: uuid */
            readonly id: string;
            /** Titre */
            title: string;
            /** Format: date */
            date: string;
            /**
             * Heure de début
             * Format: time
             */
            start_time: string;
            /**
             * Heure de fin
             * Format: time
             */
            end_time: string;
            /** Type de lieu */
            location_kind: components["schemas"]["LocationKindEnum"];
            readonly location_label: string;
            /**
             * Lien de visioconférence
             * Format: uri
             */
            online_url: string;
            /** @description The postal address on one line, or "" for an online workshop. */
            readonly address: string;
            description: string;
        };
        /**
         * @description * `online` - En ligne
         *     * `onsite` - Sur place
         * @enum {string}
         */
        LocationKindEnum: "online" | "onsite";
        /**
         * @description One tariff line.
         *
         *     `amount` goes out as a decimal string (DRF's default, which avoids float rounding) or
         *     null when the tariff is on demand. The frontend formats it with Intl.NumberFormat —
         *     the euro sign never enters the data.
         */
        Price: {
            /** Format: uuid */
            readonly id: string;
            /** Libellé */
            description: string;
            /**
             * Montant
             * Format: decimal
             * @description En euros. Laisser vide si le tarif est sur devis.
             */
            amount: string | null;
            /**
             * Sur devis
             * @description Cocher pour afficher « Sur devis » à la place d'un montant.
             */
            on_demand: boolean;
        };
        /**
         * @description A tariff group with its lines nested.
         *
         *     Nested rather than a second endpoint because the site renders exactly this shape —
         *     one card per group, a list of lines inside it. One request, and no chance of the two
         *     halves arriving inconsistent.
         *
         *     Which lines are visible is decided once, in the view's Prefetch — not here. A plain
         *     nested serializer then types itself in the OpenAPI schema, where a SerializerMethodField
         *     would have needed an @extend_schema_field to say what it returns.
         */
        PricingType: {
            /** Format: uuid */
            readonly id: string;
            /** Nom */
            name: string;
            /** @description Note affichée sous les tarifs de ce groupe. */
            description: string;
            readonly prices: components["schemas"]["Price"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    events_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
        };
    };
    pricing_types_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingType"][];
                };
            };
        };
    };
}
